# Generated by Django 3.1.6 on 2021-02-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('teacher', models.CharField(max_length=15)),
                ('loc', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='images/%Y%m')),
                ('online', models.BooleanField(default=False)),
                ('sys', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
